# AWS Configuration
AWS_DEFAULT_REGION = "us-west-2"

# Bedrock Agent Configuration
BEDROCK_AGENT_ID = "EXXUAANZ3U"
BEDROCK_AGENT_ALIAS_ID = "MX9HRBFXQG"
BEDROCK_KNOWLEDGE_BASE_ID = "MV3XHZYTNA"

# S3 Configuration
S3_BUCKET_NAME = "tablered5-s3"

# AWS Credentials (you'll need to add these in the Streamlit Cloud dashboard)
# Do not commit actual credentials to this file
[aws_credentials]
AWS_ACCESS_KEY_ID = "ASIAVGULTSFQYRMSW5RE"
AWS_SECRET_ACCESS_KEY = "YIdcRgczocK0QX7wzzx114xyQl5+kGSLQcueOvNQ"
